server {
    server_name bautistaj.dev;
    root /home/admin/persist/btaj-mx-tour/www;
    index index.html;

    location ~* \.(png|jpg|jpeg|webp)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /home/admin/persist/btaj-mx-tour/www;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/bautistaj.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bautistaj.dev/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}
