server {
    server_name bautistaj.dev;

    location /btaj-tour/ {
        root /home/admin/persist/btaj-mx-tour;
        index index.html;
        try_files $uri $uri/ /btaj-tour/index.html;
    }

    error_page 500 502 503 504 /50x.html;

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/bautistaj.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bautistaj.dev/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}
